# .github/workflows/deploy.yml
name: Deploy Cloud Run 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying portfolio app
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: stone-goal-401904

      - name: Building ()
        run: |-
          gcloud builds submit \
            --tag gcr.io/stone-goal-401904/portfolio-project --project=stone-goal-401904

      # Setup gcloud CLI

      - name: Deploy ()
        uses: google-github-actions/deploy-cloudrun@v2
        with:
            service: portfolio-project
            image: gcr.io/stone-goal-401904/portfolio-project
            region: asia-northeast1
            project_id: stone-goal-401904