# .github/workflows/deploy.yml
name: Deploy Cloud Run 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying  Clima
    runs-on: ubuntu-latest
    if: "github.event.head_commit.message, 'to deploy'"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: "YOUR_EMAIL"
          project_id: YOUR_PROJECT_ID

      - name: Building ()
        run: |-
          gcloud builds submit \
            --tag gcr.io/stone-goal-401904/portfolio-project

      # Setup gcloud CLI
      - name: Deploy ()
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: portfolio-project
          image: gcr.io/stone-goal-401904/portfolio-project
          region: asia-northeast1
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: stone-goal-401904